# Generated by Django 3.1.7 on 2021-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPMN',
            fields=[
                ('id_bpmn', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bpmn', models.CharField(max_length=25)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bpmn',
            },
        ),
        migrations.CreateModel(
            name='TextUserStory',
            fields=[
                ('id_text_us', models.AutoField(primary_key=True, serialize=False)),
                ('text_who', models.CharField(max_length=25)),
                ('text_what', models.CharField(max_length=25)),
                ('text_why', models.CharField(max_length=25, null=True)),
                ('nama_us', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'text_user_stories',
            },
        ),
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id_us', models.AutoField(primary_key=True, serialize=False)),
                ('nama_us', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_stories',
            },
        ),
    ]
