# Generated by Django 3.1.7 on 2021-06-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn_to_us', '0002_auto_20210625_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textuserstory',
            name='nama_us',
        ),
    ]
